### ISSUE TITLE
error: failed to run custom build command for `rust-crypto v0.2.36`

### ISSUE THREAD

**Issue by zhuxiujia** [DaGenix/rust-crypto#464]
```rust
error: failed to run custom build command for `rust-crypto v0.2.36`

Caused by:
  process didn't exit successfully: `D:\RustProject\abs_admin\target\debug\build\rust-crypto-7dab7e69e58efb4c\build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-pc-windows-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-m64" "-Wall" "-Wextra" "-o" "D:\\RustProject\\abs_admin\\target\\debug\\build\\rust-crypto-c8531fa22b25e07d\\out\\src/util_helpers.o" "-c" "src/util_helpers.c"

--- stderr
thread 'main' panicked at '

Internal error occurred: Failed to find tool. Is `cc` installed? (see https://github.com/alexcrichton/gcc-rs#compile-time-requirements for help)

', C:\Users\mayn\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.55\src\lib.rs:1672:5
stack backtrace:
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace/dbghelp.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src\libstd\sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src\libstd\sys_common/backtrace.rs:59
   4: core::fmt::write
             at src\libcore\fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src\libstd\io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src\libstd\sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src\libstd\sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src\libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src\libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src\libstd/panicking.rs:486
  11: rust_begin_unwind
             at src\libstd/panicking.rs:388
  12: std::panicking::begin_panic_fmt
             at src\libstd/panicking.rs:342
  13: gcc::fail
             at C:\Users\mayn\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.55\src/lib.rs:1672
  14: gcc::Build::compile
             at C:\Users\mayn\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.55\src/lib.rs:785
  15: build_script_build::main
             at .\build.rs:38
  16: std::rt::lang_start::{{closure}}
             at C:\Users\mayn\.rustup\toolchains\stable-x86_64-pc-windows-gnu\lib/rustlib/src/rust\src\libstd/rt.rs:67
  17: std::rt::lang_start_internal::{{closure}}
             at src\libstd/rt.rs:52
  18: std::panicking::try::do_call
             at src\libstd/panicking.rs:297
  19: std::panicking::try
             at src\libstd/panicking.rs:274
  20: std::panic::catch_unwind
             at src\libstd/panic.rs:394
  21: std::rt::lang_start_internal
             at src\libstd/rt.rs:51
  22: std::rt::lang_start
             at C:\Users\mayn\.rustup\toolchains\stable-x86_64-pc-windows-gnu\lib/rustlib/src/rust\src\libstd/rt.rs:67
  23: main
  24: __tmainCRTStartup
             at C:/crossdev/src/mingw-w64-v4-git/mingw-w64-crt/crt/crtexe.c:332
  25: mainCRTStartup
             at C:/crossdev/src/mingw-w64-v4-git/mingw-w64-crt/crt/crtexe.c:212
  26: units_search
  27: units_search
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
````

**Comment by newpavlov** [comment]
This crate is unmaintained, it's strongly recommended to use other crates instead.

https://rustsec.org/advisories/RUSTSEC-2016-0005.html
